package viewer;

import controlConnetion.conectaBanco;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import modelBeans.Table;
import modelBeans.focusTraversalPolicy;

public final class Clientes extends javax.swing.JFrame {

    conectaBanco conexao = new conectaBanco();
    PreparedStatement stmt = null;
    ResultSet rs = null;
    String nome;
    int idVenda;
    JFrame frame;
    JDialog dialog;

    public Clientes() {
        initComponents();
        componentes();
        controlFocus();
        readTableCliente("select * from cliente where nome!='0' order by nome");
        tabelaCliente.getTableHeader().setDefaultRenderer(new Clientes.header()); 
    }

    public void componentes() {

        barTable.getViewport().setBackground(Color.WHITE);
    }

    public void controlFocus() {
        ArrayList<Component> order = new ArrayList<>(3);
        order.add(getContentPane());
        order.add(caixa);
        order.add(barraPesquisa);
        focusTraversalPolicy policy = new focusTraversalPolicy(order);
        setFocusTraversalPolicy(policy);
    }

    static public class header extends DefaultTableCellRenderer {

        @SuppressWarnings("OverridableMethodCallInConstructor")
        public header() {
            setOpaque(true);
        }

        @Override
        public Component getTableCellRendererComponent(JTable jtable, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(jtable, value, selected, focused, row, column);
            setBackground(new Color(033, 108, 138));
            setForeground(new Color(255, 255, 255));
            setFont(new Font("Arial", Font.BOLD, 16));
            setHorizontalAlignment(JLabel.CENTER);
            return super.getTableCellRendererComponent(jtable, value, selected, focused, row, column);
        }
    }

    @SuppressWarnings("CallToPrintStackTrace")
    public void readTableCliente(String Sql) {
        conexao.conecta();
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"id", "Nome", "Celular", "Endereço"};
        conexao.executaSQL(Sql);
        try {
            conexao.rs.first();
            do {
                dados.add(new Object[]{
                    conexao.rs.getString("idCliente"), conexao.rs.getString("nome"),
                    conexao.rs.getString("celular"), conexao.rs.getString("endereco")});
            } while (conexao.rs.next());
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
        Table tabela = new Table(dados, colunas);

        DefaultTableCellRenderer esquerda = new DefaultTableCellRenderer();
        DefaultTableCellRenderer centralizado = new DefaultTableCellRenderer();
        DefaultTableCellRenderer direita = new DefaultTableCellRenderer();
        esquerda.setHorizontalAlignment(SwingConstants.LEFT);
        centralizado.setHorizontalAlignment(SwingConstants.CENTER);
        direita.setHorizontalAlignment(SwingConstants.RIGHT);

        tabelaCliente.setModel(tabela);
        tabelaCliente.getColumnModel().getColumn(0).setPreferredWidth(100);
        tabelaCliente.getColumnModel().getColumn(0).setResizable(false);
        tabelaCliente.getColumnModel().getColumn(0).setMinWidth(0);
        tabelaCliente.getColumnModel().getColumn(0).setMaxWidth(0);
        tabelaCliente.getColumnModel().getColumn(1).setPreferredWidth(308);
        tabelaCliente.getColumnModel().getColumn(1).setResizable(false);
        tabelaCliente.getColumnModel().getColumn(2).setPreferredWidth(250);
        tabelaCliente.getColumnModel().getColumn(2).setResizable(false);
        tabelaCliente.getColumnModel().getColumn(3).setPreferredWidth(450);
        tabelaCliente.getColumnModel().getColumn(3).setResizable(false);
        tabelaCliente.getTableHeader().setReorderingAllowed(false);
        tabelaCliente.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tabelaCliente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conexao.desconecta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        caixa = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        barraPesquisa = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        barTable = new javax.swing.JScrollPane();
        tabelaCliente = new javax.swing.JTable();
        botPesquisa = new javax.swing.JButton();
        botExcluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        botAtualizar = new javax.swing.JButton();
        botAdicionar = new javax.swing.JButton();
        botVenda = new javax.swing.JButton();
        botMostrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tela de Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 24))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caixa.setFont(new java.awt.Font("Segoe UI Symbol", 0, 16)); // NOI18N
        caixa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  Nome", "  Celular" }));
        caixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caixaKeyPressed(evt);
            }
        });
        jPanel1.add(caixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 131, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 16)); // NOI18N
        jLabel2.setText("Palavra Chave:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        barraPesquisa.setFont(new java.awt.Font("Segoe UI Semilight", 0, 16)); // NOI18N
        barraPesquisa.setBorder(null);
        barraPesquisa.setOpaque(false);
        barraPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barraPesquisaKeyPressed(evt);
            }
        });
        jPanel1.add(barraPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 350, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 350, 10));

        tabelaCliente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tabelaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabelaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaClienteMouseClicked(evt);
            }
        });
        barTable.setViewportView(tabelaCliente);

        jPanel1.add(barTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 970, 490));

        botPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/buscar 32.png"))); // NOI18N
        botPesquisa.setToolTipText("Pesquisar");
        botPesquisa.setContentAreaFilled(false);
        botPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botPesquisaActionPerformed(evt);
            }
        });
        jPanel1.add(botPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 35, 35));

        botExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/lixeira 32.png"))); // NOI18N
        botExcluir.setToolTipText("Excluir");
        botExcluir.setContentAreaFilled(false);
        botExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botExcluirActionPerformed(evt);
            }
        });
        jPanel1.add(botExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 35, 35));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 13)); // NOI18N
        jLabel3.setText("Quero pesquisar por:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        botAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atualizar 32.png"))); // NOI18N
        botAtualizar.setToolTipText("Atualizar Tabela");
        botAtualizar.setContentAreaFilled(false);
        botAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAtualizarActionPerformed(evt);
            }
        });
        jPanel1.add(botAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 35, 35));

        botAdicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add 40.png"))); // NOI18N
        botAdicionar.setToolTipText("Adicionar Cliente");
        botAdicionar.setContentAreaFilled(false);
        botAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(botAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 35, 35));

        botVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/venda preto 32.png"))); // NOI18N
        botVenda.setToolTipText("Adicionar Cliente");
        botVenda.setContentAreaFilled(false);
        botVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botVendaActionPerformed(evt);
            }
        });
        jPanel1.add(botVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 30, 35));

        botMostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/open 40.png"))); // NOI18N
        botMostrar.setToolTipText("Mostrar");
        botMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botMostrarMouseClicked(evt);
            }
        });
        jPanel1.add(botMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1040, 699));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void caixaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caixaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (caixa.getSelectedItem().equals("  Celular")) {
                readTableCliente("select * from cliente where celular='" + barraPesquisa.getText() + "'");
            }
            if (caixa.getSelectedItem().equals("  Nome")) {
                readTableCliente("select * from cliente where nome='" + barraPesquisa.getText() + "'");
            }
        }
    }//GEN-LAST:event_caixaKeyPressed

    private void barraPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barraPesquisaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (caixa.getSelectedItem().equals("  Celular")) {
                readTableCliente("select * from cliente where celular='" + barraPesquisa.getText() + "'");
            }
            if (caixa.getSelectedItem().equals("  Nome")) {
                readTableCliente("select * from cliente where nome='" + barraPesquisa.getText() + "'");
            }
        }
    }//GEN-LAST:event_barraPesquisaKeyPressed

    private void tabelaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaClienteMouseClicked
        int linha = tabelaCliente.getSelectedRow();
        nome = tabelaCliente.getValueAt(linha, 1).toString();
    }//GEN-LAST:event_tabelaClienteMouseClicked

    private void botPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botPesquisaActionPerformed
        if (caixa.getSelectedItem().equals("  Celular")) {
            readTableCliente("select * from cliente where celular='" + barraPesquisa.getText() + "'");
        }
        if (caixa.getSelectedItem().equals("  Nome")) {
            readTableCliente("select * from cliente where nome='" + barraPesquisa.getText() + "'");
        }
    }//GEN-LAST:event_botPesquisaActionPerformed

    private void botExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botExcluirActionPerformed
        int linha = tabelaCliente.getSelectedRow();
        String codigo = tabelaCliente.getValueAt(linha, 0).toString();

        int resposta = JOptionPane.showConfirmDialog(null, "Deseja excluir este cliente?");
        if (resposta == JOptionPane.YES_OPTION) {
            conexao.conecta();
            try {
                stmt = conexao.conn.prepareStatement("delete from cliente where idCliente='" + codigo + "'");
                stmt.execute();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
        conexao.desconecta();
        readTableCliente("select * from cliente order by nome");
    }//GEN-LAST:event_botExcluirActionPerformed

    private void botAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAtualizarActionPerformed
        readTableCliente("select * from cliente order by nome");
    }//GEN-LAST:event_botAtualizarActionPerformed

    private void botAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botAdicionarActionPerformed
        new AddClientes(this, true).setVisible(true);
    }//GEN-LAST:event_botAdicionarActionPerformed

    private void botVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botVendaActionPerformed
        new VendaFiador(this, nome).setVisible(true);
    }//GEN-LAST:event_botVendaActionPerformed

    private void botMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botMostrarMouseClicked
        new ComprasClientes(this, true, nome).setVisible(true);
    }//GEN-LAST:event_botMostrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Clientes().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane barTable;
    private javax.swing.JTextField barraPesquisa;
    private javax.swing.JButton botAdicionar;
    private javax.swing.JButton botAtualizar;
    private javax.swing.JButton botExcluir;
    private javax.swing.JLabel botMostrar;
    private javax.swing.JButton botPesquisa;
    private javax.swing.JButton botVenda;
    private javax.swing.JComboBox<String> caixa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTable tabelaCliente;
    // End of variables declaration//GEN-END:variables
}
